### ISSUE TITLE
Comments box is obscured on Android

### ISSUE THREAD

**Issue by vinaynagappala** [williamchong256/immersive-sleep#67]
**Describe the bug**
On Android, when typing in the comments box, the navigation bar moves with the keyboard. 

**To Reproduce**

1. Go to Data Tab. 
2. Click on any date. 
3. Select the comments box.
4. See error.

**Expected behavior**
The navigation bar should not move with the keyboard.

**Screenshots**

**Smartphone (please complete the following information):**
![Screenshot_20210125-153506_Expo](https://user-images.githubusercontent.com/73803304/105779865-16beda80-5f24-11eb-85e7-3b3cd8b6c8b0.jpg)

- Device: Samsung Galaxy S9
- OS: Android 10, OneUI 2.5

**Comment by Firius0408** [comment]
A quick google search lead to this react navigation issue [here](https://github.com/react-navigation/react-navigation/issues/6700). I'll see if I can fix it based on that but @vinaynagappala I'll most likely need you to test it because I don't have an Android emulator on me.

**Comment by Firius0408** [comment]
@vinaynagappala Can you checkout branch patch-67 and see if my hot fix works?

**Comment by Firius0408** [comment]
This fix modifies the AndroidManifest.xml file through Expo which should change how the keyboard resizes on Android. If this doesn't work, there's an option in react navigation to hide the tab bar when the keyboard is shown, but that causes a hiding and displaying animation that can sometimes be seen.
