### ISSUE TITLE
Dropdown choices in profile tab do not save

### ISSUE THREAD

**Issue by courtneylau** [williamchong256/immersive-sleep#76]
**Describe the bug**
Dropdown choices for age and duration (goal duration of sleep) under profile tab do not save.

**To Reproduce**

1. Go to Profile tab under Settings.
2. Click on 'Select options' by 'Age' or 'Duration' and select a non default value.
3. Go to a different tab.
4. Return to Profile tab. Dropdown choice will have returned to 'Select options'.

**Expected behavior**
Dropdown choice should stay the same even after leaving the page. Should be able to fix the same way as the comments box was fixed.

**Comment by Firius0408** [comment]
Yeah they're not saving for the same reason the comments didn't save before. However, in this case we want the user information to be synced with AWS, so I can't just do the same thing as I did last time with AsyncStorage, as that saved comments to the frontend only. I'll work on this bug fix after we get your profile page to integrate with AWS, as I also need to modify the AWS user pool to match the attributes you defined on the frontend.

**Comment by Firius0408** [comment]
@courtneylau Is this issue still in progress?

**Comment by Firius0408** [comment]
Closing this as stale and integrated into aws-amplify branch
