### ISSUE TITLE
Migrate frontend branch to main

### ISSUE THREAD

**Issue by Firius0408** [williamchong256/immersive-sleep#86]
**Is your feature request related to a problem? Please describe.**
A while back, @williamchong256 suggested consolidating our branches and eliminating branches like frontend and backend. I shot down that idea at the time, because we were still planning on a Node.js backend. Now that we're going the AWS backend route, the backend branch is stale, and we don't need to keep these branches separate anymore.

**Describe the solution you'd like**
We should merge the frontend branch into main and instead base our PRs into main instead of frontend. Currently, frontend branch sits as a holding branch because no work is being done on any other branches, now that the backend branch is stale.

**Comment by williamchong256** [comment]
Got it, so there wouldn't be much benefit from keeping a software and hardware branch?

**Comment by Firius0408** [comment]
Well the reality is it's mostly going to be software that's pushing commits and making changes to the repository, whereas hardware might upload some files every so often. Keeping branches separate is helpful when changes are being made on both sides that would conflict if everything was done on one branch. Because hardware rarely pushes commits, and when they do so far it's always been into the hardware/ directory, there isn't much reason to have the extra step between frontend branch and the main branch.

**Comment by williamchong256** [comment]
Makes sense, let's merge them then.
