### ISSUE TITLE
Consider migrating existing usage of AsyncStorage and SQLite in Expo to DataStore in AWS

### ISSUE THREAD

**Issue by Firius0408** [williamchong256/immersive-sleep#97]
Currently, some data, like Comments in Detailed Data page and Lighting settings, are stored locally on device, either through AsyncStorage or SQLite. With our AWS backend, we have the ability to store preference data like this in the cloud, so that the data can persist across devices. In this way, the data is tied to a specific user, instead of a specific device. This change may be desirable but it may also not be. Discussion regarding whether or not we should make this change should be done below.

**Comment by Firius0408** [comment]
Any thoughts?

**Comment by jpicchi18** [comment]
I think that it may be cool to have the data tied to a particular user, if that change is not too difficult. If it is difficult/has significant disadvantages, then I think that the current implementation using local storage will work for our purposes.

**Comment by Firius0408** [comment]
Nah it won't be too difficult. I'm gonna set up our data models in #96 and I'll include these data as well, once we finalize our data models.

**Comment by jpicchi18** [comment]
sounds great!

**Comment by williamchong256** [comment]
sounds like a good feature to add, I vote yes

**Comment by vinaynagappala** [comment]
Yeah, I agree that using AWS makes a lot of sense. Will it be noticeably slower than using AsyncStorage/SQLite?

**Comment by Firius0408** [comment]
No, once the data is synced from the cloud, the data is stored locally and kept in sync in the background.
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js

**Comment by Firius0408** [comment]
DataStore shouldn't be used to store data like this so I'm gonna have to migrate everything to GraphQL API
